package com.safezone.app.models;

/**
 * LinkToken Model
 * Represents a token generated by parent for child linking via QR code
 * Token expires after 10 minutes
 */
public class LinkToken {
    private String tokenId;
    private String parentUid;
    private String parentEmail;
    private String parentName;
    private String childUid;
    private long createdAt;
    private long expiresAt;
    private boolean used;
    private String childName;

    // Empty constructor for Firebase
    public LinkToken() {
    }

    /**
     * Constructor for creating a new token
     * @param tokenId Unique token identifier
     * @param parentUid Parent's Firebase UID
     * @param childName Child's name (for display)
     */
    public LinkToken(String tokenId, String parentUid, String childName) {
        this.tokenId = tokenId;
        this.parentUid = parentUid;
        this.childName = childName;
        this.createdAt = System.currentTimeMillis();
        this.expiresAt = this.createdAt + (10 * 60 * 1000); // 10 minutes
        this.used = false;
        this.childUid = null;
    }
    
    /**
     * Constructor for creating a new token with parent info
     * @param tokenId Unique token identifier
     * @param parentUid Parent's Firebase UID
     * @param parentEmail Parent's email
     * @param parentName Parent's name
     * @param childName Child's name (for display)
     */
    public LinkToken(String tokenId, String parentUid, String parentEmail, String parentName, String childName) {
        this.tokenId = tokenId;
        this.parentUid = parentUid;
        this.parentEmail = parentEmail;
        this.parentName = parentName;
        this.childName = childName;
        this.createdAt = System.currentTimeMillis();
        this.expiresAt = this.createdAt + (10 * 60 * 1000); // 10 minutes
        this.used = false;
        this.childUid = null;
    }

    /**
     * Check if token is expired
     * @return true if current time is past expiry time
     */
    public boolean isExpired() {
        return System.currentTimeMillis() > expiresAt;
    }

    /**
     * Check if token is valid (not expired and not used)
     * @return true if token can be used
     */
    public boolean isValid() {
        return !isExpired() && !used;
    }

    /**
     * Get remaining time in milliseconds
     * @return milliseconds until expiry, or 0 if expired
     */
    public long getRemainingTimeMillis() {
        long remaining = expiresAt - System.currentTimeMillis();
        return Math.max(0, remaining);
    }

    /**
     * Get remaining time in seconds
     * @return seconds until expiry
     */
    public long getRemainingTimeSeconds() {
        return getRemainingTimeMillis() / 1000;
    }

    /**
     * Mark token as used after successful child linking
     * @param childUid Child's Firebase UID
     */
    public void markAsUsed(String childUid) {
        this.used = true;
        this.childUid = childUid;
    }

    // Getters and Setters
    public String getTokenId() {
        return tokenId;
    }

    public void setTokenId(String tokenId) {
        this.tokenId = tokenId;
    }

    public String getParentUid() {
        return parentUid;
    }

    public void setParentUid(String parentUid) {
        this.parentUid = parentUid;
    }

    public String getChildUid() {
        return childUid;
    }

    public void setChildUid(String childUid) {
        this.childUid = childUid;
    }

    public long getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(long createdAt) {
        this.createdAt = createdAt;
    }

    public long getExpiresAt() {
        return expiresAt;
    }

    public void setExpiresAt(long expiresAt) {
        this.expiresAt = expiresAt;
    }

    public boolean isUsed() {
        return used;
    }

    public void setUsed(boolean used) {
        this.used = used;
    }

    public String getChildName() {
        return childName;
    }

    public void setChildName(String childName) {
        this.childName = childName;
    }
    
    public String getParentEmail() {
        return parentEmail;
    }

    public void setParentEmail(String parentEmail) {
        this.parentEmail = parentEmail;
    }

    public String getParentName() {
        return parentName;
    }

    public void setParentName(String parentName) {
        this.parentName = parentName;
    }
}